# Generated by Django 3.0.4 on 2020-03-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0004_auto_20200320_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(default='No tag', on_delete=django.db.models.deletion.CASCADE, to='notetaking.Tag'),
        ),
    ]
