# Generated by Django 3.0.4 on 2020-04-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0006_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('title', 'tag')},
        ),
    ]
