# Generated by Django 3.0.4 on 2020-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0007_auto_20200331_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(error_messages={'unique': '%(model_name)s tag already exist.'}, max_length=100, primary_key=True, serialize=False),
        ),
    ]
